import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import TopNav from "@/components/TopNav";
import { Toaster } from "@/components/ui/sonner";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`font-sans ${inter} dark`}>
        <TopNav />
        {children}
        <Toaster />
        <footer className="bg-primary-foreground absolute bottom-0 w-full p-3 text-white py-4 flex justify-between items-center">
          <p>© 2024 James Wallinder</p>
          <ul className="flex justify-between px-4 gap-4">
            <li>
              <Link
                href="https://github.com/jwallinder99/mira-lotto"
                className="hover:text-gray-400"
              >
                Github
              </Link>
            </li>
            <li>
              <Link
                href="https://my-portfolio-ifcsc0368-james-projects-2d2118f9.vercel.app/"
                className="hover:text-gray-400"
              >
                Portfolio
              </Link>
            </li>
            <li>
              <Link
                href="https://www.linkedin.com/in/james-wallinder-66114a186/"
                className="hover:text-gray-400"
              >
                LinkedIn
              </Link>
            </li>
          </ul>
        </footer>
      </body>
    </html>
  );
}
